apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoringapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoringapp
  template:
    metadata:
      labels:
        app: monitoringapp
    spec:
      containers:
        - name: monitoringapp
          image: 172165467462.dkr.ecr.ap-south-1.amazonaws.com/monitoringapp:latest
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: monitoringapp
spec:
  selector:
    app: monitoringapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

